/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "primary": "#af101a",
        "outline": "#8f6f6c",
        "surface-container-high": "#e8e8e8",
        "tertiary-container": "#5e67c2",
        "primary-container": "#d32f2f",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "on-primary-fixed": "#410003",
        "on-secondary-fixed": "#2a1800",
        "on-surface-variant": "#5b403d",
        "on-surface": "#1a1c1c",
        "tertiary": "#454ea7",
        "error": "#ba1a1a",
        "on-background": "#1a1c1c",
        "surface-dim": "#dadada",
        "surface-tint": "#ba1a20",
        "primary-fixed": "#ffdad6",
        "surface-bright": "#f9f9f9",
        "secondary": "#835400",
        "on-tertiary-fixed": "#000767",
        "surface-container-low": "#f3f3f3",
        "tertiary-fixed": "#e0e0ff",
        "on-tertiary-container": "#f5f2ff",
        "on-primary-container": "#fff2f0",
        "on-secondary-container": "#694300",
        "error-container": "#ffdad6",
        "surface-container": "#eeeeee",
        "surface": "#f9f9f9",
        "secondary-fixed-dim": "#ffb957",
        "on-tertiary-fixed-variant": "#343d96",
        "on-primary-fixed-variant": "#930010",
        "outline-variant": "#e4beba",
        "tertiary-fixed-dim": "#bdc2ff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e2e2e2",
        "inverse-surface": "#2f3131",
        "surface-container-highest": "#e2e2e2",
        "on-error": "#ffffff",
        "background": "#f9f9f9",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb3ac",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffddb5",
        "secondary-container": "#fcab28",
        "on-secondary-fixed-variant": "#643f00",
        "primary-fixed-dim": "#ffb3ac"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "base": "8px",
        "gutter": "24px",
        "container-max": "1200px"
      },
      "fontFamily": {
        "display-lg-mobile": ["Noto Sans TC"],
        "display-lg": ["Noto Sans TC"],
        "label-sm": ["Noto Sans TC"],
        "headline-sm": ["Noto Sans TC"],
        "label-md": ["Noto Sans TC"],
        "body-md": ["Noto Sans TC"],
        "body-lg": ["Noto Sans TC"],
        "headline-md": ["Noto Sans TC"]
      },
      "fontSize": {
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "display-lg": ["40px", { "lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-sm": ["22px", { "lineHeight": "30px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["28px", { "lineHeight": "36px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
